name: "setup-expo"
description: "Setup Expo builds"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v5.0.0
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/actions/setup-gradle@v5

    - uses: expo/expo-github-action@v8
      with:
        expo-version: latest

    - uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: expo/package-lock.json

    - run: npm ci
      shell: bash
      working-directory: expo

    - run: npx expo export --platform android
      shell: bash
      working-directory: expo
