name: "setup-native-android"
description: "Setup native Android builds"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v5.0.0
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/actions/setup-gradle@v4
