name: Android CI

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ORG_GRADLE_PROJECT_GIPHY_API_KEY: ${{ secrets.ORG_GRADLE_PROJECT_GIPHY_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v3.0.0
        with:
          arguments: test --stacktrace

  connectedAndroidTest:
    runs-on: ubuntu-latest
    steps:
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - uses: reactivecircus/android-emulator-runner@v2.30.1
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest

  assembleDebug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v3.0.0
        with:
          arguments: assembleDebug --stacktrace

      - uses: actions/upload-artifact@v4.3.0
        with:
          name: rlad-debug-apk
          path: app/build/outputs/apk/debug/*debug*.apk

  assembleRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v3.0.0
        with:
          arguments: assembleRelease --stacktrace

      - uses: ilharp/sign-android-release@v1.0.4
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.RELEASE_SIGNING_KEY }}
          keyAlias: ${{ secrets.RELEASE_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - uses: actions/upload-artifact@v4.3.0
        with:
          name: rlad-release-apk
          path: ${{steps.sign_app.outputs.signedFile}}

  bundleRelease:
    if: github.ref == 'refs/heads/master'
    needs: [ test, connectedAndroidTest, assembleDebug, assembleRelease ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number}}
          versionName: '1.0.${{github.run_number}}'

      - uses: gradle/gradle-build-action@v3.0.0
        with:
          arguments: bundleRelease --stacktrace

      - uses: ilharp/sign-android-release@v1.0.4
        id: sign_app
        with:
          releaseDir: app/build/outputs/bundle/release
          signingKey: ${{ secrets.RELEASE_SIGNING_KEY }}
          keyAlias: ${{ secrets.RELEASE_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - uses: actions/upload-artifact@v4.3.0
        with:
          name: rlad-release-bundle
          path: ${{steps.sign_app.outputs.signedFile}}

      - uses: r0adkll/upload-google-play@v1.1.2
        with:
          serviceAccountJsonPlainText: ${{ secrets.RELEASE_SERVICE_ACCOUNT_JSON }}
          packageName: com.rlad
          releaseFiles: ${{steps.sign_app.outputs.signedFile}}
