name: Android CI

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ORG_GRADLE_PROJECT_GIPHY_API_KEY: ${{ secrets.ORG_GRADLE_PROJECT_GIPHY_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test --stacktrace

  connectedAndroidTest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest

  assembleDebug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug --stacktrace

      - uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  assembleRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease --stacktrace

      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.RELEASE_SIGNING_KEY }}
          alias: ${{ secrets.RELEASE_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

  bundleRelease:
    if: github.ref == 'refs/heads/master'
    needs: [ test, connectedAndroidTest, assembleDebug, assembleRelease ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: chkfung/android-version-actions@v1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number}}
          versionName: '1.0.${{github.run_number}}'

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: bundleRelease --stacktrace

      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.RELEASE_SIGNING_KEY }}
          alias: ${{ secrets.RELEASE_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: app-bundle-release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.RELEASE_SERVICE_ACCOUNT_JSON }}
          packageName: com.rlad
          track: production
          status: completed
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
