name: expo

on:
  push:
    paths:
      - "expo/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  EXPO_PUBLIC_GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}

jobs:
  bundleRelease:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: expo/package-lock.json

      - uses: actions/setup-java@v4.7.1
        with:
          distribution: temurin
          java-version: 17

      - uses: expo/expo-github-action@v8
        with:
          expo-version: latest

      - run: npm ci
        working-directory: expo

      - name: Update app version
        working-directory: expo
        run: |
          node -e "
            const fs = require('fs');
            const config = JSON.parse(fs.readFileSync('app.json', 'utf8'));
            const versionCode = ${{ github.run_number }};
            config.expo.version = '1.0.' + versionCode;
            config.expo.android.versionCode = versionCode;
            fs.writeFileSync('app.json', JSON.stringify(config, null, 2));
          "

      - working-directory: expo
        run: npx expo export --platform android

      - uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: bundleRelease --stacktrace
          build-root-directory: expo/android

      - uses: ilharp/sign-android-release@v2.0.0
        id: sign_app
        with:
          releaseDir: expo/android/app/build/outputs/bundle/release
          signingKey: ${{ secrets.RELEASE_SIGNING_KEY }}
          keyAlias: ${{ secrets.RELEASE_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: rlad-expo-release-bundle
          path: ${{steps.sign_app.outputs.signedFile}}

      - uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.RELEASE_SERVICE_ACCOUNT_JSON }}
          packageName: com.rlad.expo
          releaseFiles: ${{steps.sign_app.outputs.signedFile}}
