name: expo

on:
  push:
    paths:
      - "expo/**"
      - ".github/workflows/expo.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  EXPO_PUBLIC_GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}

jobs:
  assembleDebug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0

      - uses: ./.github/actions/setup-expo

      - run: ./gradlew assembleDebug --stacktrace
        working-directory: expo/android

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: rlad-expo-debug-apk
          path: expo/android/app/build/outputs/apk/debug/*debug*.apk

  assembleRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0

      - uses: ./.github/actions/setup-expo

      - run: ./gradlew assembleRelease --stacktrace
        working-directory: expo/android

      - uses: ilharp/sign-android-release@v2.0.0
        id: sign_app
        with:
          releaseDir: expo/android/app/build/outputs/apk/release
          signingKey: ${{ secrets.RELEASE_SIGNING_KEY }}
          keyAlias: ${{ secrets.RELEASE_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: rlad-expo-release-apk
          path: ${{steps.sign_app.outputs.signedFile}}

  bundleRelease:
    if: github.ref == 'refs/heads/master'
    needs: [assembleDebug, assembleRelease]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0

      - uses: ./.github/actions/setup-expo

      - uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: expo/android/app/build.gradle
          versionCode: ${{ github.run_number }}
          versionName: "1.0.${{ github.run_number }}"

      - run: ./gradlew bundleRelease --stacktrace
        working-directory: expo/android

      - uses: ilharp/sign-android-release@v2.0.0
        id: sign_app
        with:
          releaseDir: expo/android/app/build/outputs/bundle/release
          signingKey: ${{ secrets.RELEASE_SIGNING_KEY }}
          keyAlias: ${{ secrets.RELEASE_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: rlad-expo-release-bundle
          path: ${{steps.sign_app.outputs.signedFile}}

      - uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.RELEASE_SERVICE_ACCOUNT_JSON }}
          packageName: com.rlad.expo
          releaseFiles: ${{steps.sign_app.outputs.signedFile}}
